 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: sample
   name: sample-svc
 spec:
   type: ClusterIP
   selector:
     app: sample
   ports:
   - name: sample-http
     port: 9000
     targetPort: http
